# Generated by Django 4.2.7 on 2024-07-08 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Nodule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="nodulo prueba", max_length=255)),
                ("image", models.ImageField(null=True, upload_to="nodule/images")),
                ("new", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Physicist",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("experience", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TestUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("oval", "oval"),
                            ("round", "round"),
                            ("irregular", "irregular"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "margin",
                    models.CharField(
                        choices=[
                            ("circumscribed", "circumscribed"),
                            ("microlobulated", "microlobulated"),
                            ("indistinct", "indistinct"),
                            ("angulated", "angulated"),
                            ("spiculated", "spiculated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("parallel", "parallel"),
                            ("not parallel", "not parallel"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "echogenicity",
                    models.CharField(
                        choices=[
                            ("anechoic", "anechoic"),
                            ("isoechoic", "isoechoic"),
                            ("hyperechoic", "hyperechoic"),
                            ("hypoechoic", "hypoechoic"),
                            ("heterogeneous", "heterogeneous"),
                            ("complex cystic and solid", "complex cystic and solid"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "posterior",
                    models.CharField(
                        choices=[
                            ("enhancement", "enhancement"),
                            ("no features", "no features"),
                            ("shadowing", "shadowing"),
                            ("combined pattern", "combined pattern"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "calcification",
                    models.CharField(
                        choices=[
                            ("no calcifications", "no calcifications"),
                            ("calcifications", "calcifications"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "suggestivity",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "birads",
                    models.CharField(
                        choices=[
                            ("2", "2"),
                            ("3", "3"),
                            ("4A", "4A"),
                            ("4B", "4B"),
                            ("4C", "4C"),
                            ("5", "5"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "nodule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="nodule.nodule",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="nodule_desc_content_f418a5_idx",
                    )
                ],
            },
        ),
    ]
