# Generated by Django 4.2.7 on 2024-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodule", "0002_nodule_full_image_alter_description_suggestivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="suggestivity",
            field=models.CharField(
                choices=[
                    ("simple cyst", "simple cyst"),
                    ("clustered microcysts", "clustered microcysts"),
                    ("complicated cyst", "complicated cyst"),
                    ("mass in skin", "mass in skin"),
                    ("mass on skin", "mass on skin"),
                    ("lymph node", "lymph node"),
                    ("postsurgical fluid collection", "postsurgical fluid collection"),
                    ("fat necrosis", "fat necrosis"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
