# Generated by Django 4.2.7 on 2024-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodule", "0003_alter_description_suggestivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="orientation",
            field=models.CharField(
                choices=[
                    ("parallel", "parallel"),
                    ("no orientation", "no orientation"),
                    ("not parallel", "not parallel"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
