# Generated by Django 4.2.7 on 2024-10-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodule", "0004_alter_description_orientation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodule",
            name="new",
        ),
    ]
