# Generated by Django 4.2.7 on 2024-10-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodule", "0006_nodule_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodule",
            name="new",
        ),
    ]
