# Generated by Django 4.2.7 on 2024-10-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodule", "0007_remove_nodule_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodule",
            name="new",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
