# Generated by Django 4.2.7 on 2026-02-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodule', '0008_nodule_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='nodule.ai'),
        ),
        migrations.AddField(
            model_name='description',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
