# Generated by Django 4.2.7 on 2026-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0010_migrate_description_author'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='description',
            name='nodule_desc_content_f418a5_idx',
        ),
        migrations.RemoveField(
            model_name='description',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='description',
            name='object_id',
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['user', 'nodule'], name='nodule_desc_user_id_54708a_idx'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['ai', 'nodule'], name='nodule_desc_ai_id_567e79_idx'),
        ),
        migrations.AddConstraint(
            model_name='description',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', False), ('ai__isnull', True)), models.Q(('user__isnull', True), ('ai__isnull', False)), _connector='OR'), name='description_exactly_one_author'),
        ),
    ]
