# Generated by Django 4.2.7 on 2026-02-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0011_remove_description_nodule_desc_content_f418a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicist',
            name='profession',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
