# Generated by Django 4.2.7 on 2026-02-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0012_physicist_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicist',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
