# Generated by Django 4.2.7 on 2026-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0013_alter_physicist_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicist',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
