# Generated by Django 4.2.7 on 2026-02-23 14:55

from django.db import migrations

def forwards(apps, schema_editor):
    Description = apps.get_model("nodule", "Description")
    # Convert legacy value to NULL (unselected / not assessed)
    Description.objects.filter(orientation="no orientation").update(orientation=None)


def backwards(apps, schema_editor):
    Description = apps.get_model("nodule", "Description")
    # If you ever roll back, restore NULL back to the legacy string.
    # (Even though the choice won't exist anymore, this keeps the migration reversible.)
    Description.objects.filter(orientation__isnull=True).update(orientation="no orientation")


class Migration(migrations.Migration):

    dependencies = [
        ("nodule", "0014_alter_physicist_profession"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]