# Generated by Django 4.2.7 on 2026-02-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0015_remove_no_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodule',
            name='public_full_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodule',
            name='public_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='orientation',
            field=models.CharField(choices=[('parallel', 'parallel'), ('not parallel', 'not parallel')], max_length=20, null=True),
        ),
    ]
