# Generated by Django 4.2.7 on 2026-02-27 16:55
from django.db import migrations

def fill_public_fields(apps, schema_editor):
    Nodule = apps.get_model("nodule", "Nodule")

    # Solo nodulos públicos (new = NULL)
    nodules = Nodule.objects.filter(new__isnull=True)

    for n in nodules:
        updated = False

        # Copiamos la ruta relativa del ImageField (ej: "nodule/images/BCD_158_.png")
        if n.image and not n.public_image:
            n.public_image = n.image.name
            updated = True

        if n.full_image and not n.public_full_image:
            n.public_full_image = n.full_image.name
            updated = True

        if updated:
            n.save(update_fields=["public_image", "public_full_image"])


def reverse_func(apps, schema_editor):
    # Opcional: rollback limpia los campos
    Nodule = apps.get_model("nodule", "Nodule")
    Nodule.objects.update(public_image=None, public_full_image=None)


class Migration(migrations.Migration):

    dependencies = [
        ("nodule", "0016_nodule_public_full_image_nodule_public_image_and_more"),  # ajusta esto
    ]

    operations = [
        migrations.RunPython(fill_public_fields, reverse_func),]