# Generated by Django 4.2.7 on 2026-02-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0017_fill_public_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodule',
            name='public_full_image',
        ),
        migrations.RemoveField(
            model_name='nodule',
            name='public_image',
        ),
    ]
