# Generated by Django 4.2.7 on 2026-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0018_remove_nodule_public_full_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodule',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodule',
            name='research',
            field=models.BooleanField(default=False),
        ),
    ]
