# Generated by Django 4.2.7 on 2026-04-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodule', '0019_nodule_public_nodule_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodule',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
    ]
